services:
  accounts:
    image: yurakimyurakim/accounts:0.0.1-SNAPSHOT
    container_name: accounts
    ports:
      - 8080:8080
    mem_limit: 512m
    deploy:
      resources:
        limits:
          cpus: "1.0" #prevent container cpu usage spike
          memory: 512m
    networks:
      - microservices
  loans:
    image: yurakimyurakim/loans:0.0.1-SNAPSHOT
    container_name: loans
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    networks:
      - microservices
  cards:
    image: yurakimyurakim/cards:0.0.1-SNAPSHOT
    container_name: cards
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    networks:
      - microservices

networks:
  microservices:
    driver: bridge