build:
  version: "2.0"

#AccountsContactInfoDto
accounts:
  message: "Welcome to Accounts QA"
  contactDetails:
    name: "Accounts QA Lead"
    email: "qa.accounts@microservices.com"
  onCallSupport:
    - (02)2222-2222
    - (02)2222-3333