build:
  version: "2.0"

#LoansContactInfoDto
loans:
  message: "Welcome to Loans QA"
  contactDetails:
    name: "Loans QA Lead"
    email: "qa.loans@microservices.com"
  onCallSupport:
    - (02)2222-2222
    - (02)2222-3333