build:
  version: "1.0"

#LoansContactInfoDto
loans:
  message: "Welcome to Loans"
  contactDetails:
    name: "Loans"
    email: "loans@microservices.com"
  onCallSupport:
    - (02)1111-1111
    - (02)1111-2222