services:
#1.configserver
  configserver:
    image: yurakimyurakim/configserver:0.1.0-SNAPSHOT
    container_name: configserver
    ports:
      - 8071:8071
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    networks:
      - microservices
#2.accounts
  accounts:
    image: yurakimyurakim/accounts:0.1.0-SNAPSHOT
    container_name: accounts
    ports:
      - 8080:8080
    mem_limit: 512m
    deploy:
      resources:
        limits:
          cpus: "1.0" #prevent container cpu usage spike
          memory: 512m
    networks:
      - microservices
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILE_ACTIVE: default
      #SPRING_APPLICATION_NAME: accounts
#3.loans
  loans:
    image: yurakimyurakim/loans:0.1.0-SNAPSHOT
    container_name: loans
    ports:
      - 8090:8090
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    networks:
      - microservices
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILE_ACTIVE: default
      #SPRING_APPLICATION_NAME: loans
#4.cards
  cards:
    image: yurakimyurakim/cards:0.1.0-SNAPSHOT
    container_name: cards
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512m
    networks:
      - microservices
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILE_ACTIVE: default
      #SPRING_APPLICATION_NAME: cards

networks:
  microservices:
    driver: bridge